/* eslint-disable linebreak-style */
const allStatus = {
  CODE_INTERNAL_SERVER_ERROR: 500,
  SUCCESSFUL_CODE: 200,
  NOT_FOUND_CODE: 404,
  UNAUTHORIZED_CLIENT_ERROR: 401,
  CONFLICT_RESPONSE_CODE: 409,
  CREATED_CODE: 201,
  ACCESS_FOEBIDEN: 403,
};

export default allStatus;
